#!/usr/bin/env bash
set -euo pipefail
cd -- "$(dirname "$0")"

if [ -f .env ] && ! head -n1 .env | grep -q "AUTOMATICALLY GENERATED"; then # Check if the first line is the autogen notice
  echo ".env file was manually modified. Not generating automatically." >&2
  exit 2
fi

if command -v varlock >/dev/null; then
  cmd=(varlock)
elif command -v pnpm >/dev/null; then
  cmd=(pnpm dlx varlock)
elif command -v bun >/dev/null; then
  cmd=(bunx varlock)
elif command -v npx >/dev/null; then
  cmd=(npx varlock)
else
  echo "Could not find varlock or npm. Please install it!" >&2
  echo 'You can install varlock with this command:' >&2
  echo '> curl -sSfL https://varlock.dev/install.sh | sh -s' >&2
  exit 1
fi

{
  cat <<SH
# THIS FILE IS AUTOMATICALLY GENERATED using varlock. DO NOT EDIT.
# Put your config in .env.local! See .env.schema for details.
SH
  "${cmd[@]}" load -f env
} >.env
