#!/usr/bin/env bash
set -euo pipefail
cd -- "$(dirname "$0")"

if [ -f .env ] && ! head -n1 .env | grep -q "AUTOMATICALLY GENERATED"; then # Check if the first line is the autogen notice
  echo ".env file was manually modified. Not generating automatically." >&2
  exit 2
fi

if ! command -v varlock >/dev/null; then
  echo "varlock not found. Trying to install..." >&2
  if command -v pnpm >/dev/null; then
    pnpm i -g varlock
  elif command -v yarn >/dev/null; then
    yarn global add varlock
  elif command -v bun >/dev/null; then
    bun i -g varlock
  elif command -v npm >/dev/null; then
    npm i -g varlock
  else
    echo "Could not find pnpm, yarn, bun, or npm. Please install varlock manually!" >&2
  fi
fi

if ! command -v varlock >/dev/null; then
  echo "Could not find varlock. Please install it!" >&2
  echo 'You can install varlock with this command:' >&2
  # shellcheck disable=SC2016
  echo '> curl -sSfL https://varlock.dev/install.sh | sh -s -- --dir="$HOME/.local/bin"' >&2
  exit 1
fi

code=0

if [ "${1:-}" = "all" ]; then
  echo "# Aggregating all .env files..." >&2
  file=/tmp/env.all
  true >"$file"
  for f in */.env.schema; do
    d="$(realpath "$(dirname "$f")")"
    echo "# @import($d/)" >>"$file"
  done
  echo "# ------" >>"$file"
  varlock load -p "$file" -f env || code=$?
  rm -f "$file"
  exit "$code"
fi

for f in */.env.schema; do
  d="$(dirname "$f")"
  echo "Generating $d/.env from $f"
  pushd "$d" >/dev/null
  rm -f .env
  {
    cat <<SH
# THIS FILE IS AUTOMATICALLY GENERATED using varlock. DO NOT EDIT.
# Put your config in .env.local! See .env.schema for details.
SH
    varlock load -f env || code=$?
  } >.env
  popd >/dev/null
done
exit "$code"
