# Note: this must be an absolute path
x-dockge-directory: &directory /opt/stacks

x-warnings: # A block to avoid repeating the same warnings.
  - ${DOMAIN_NAME:?You must set the domain name}
  - ${NIC_ACCESSIBLE:?NIC_ACCESSIBLE must be set}

services:
  dockge:
    image: louislam/dockge:1.5.0
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - source: *directory
        target: *directory
        type: bind
    environment:
      DOCKGE_STACKS_DIR: *directory
      DOCKGE_ENABLE_CONSOLE: true
    networks:
      - caddy
    labels:
      caddy: docker.$DOMAIN_NAME
      caddy.reverse_proxy: "{{upstreams 5001}}"
      pihole.custom-record: '[["docker.$DOMAIN_NAME", "iface:$NIC_ACCESSIBLE"]]'
networks:
  caddy:
    external: true
